services:
  db:
    image: postgres:latest
    container_name: db_habits
    volumes:
      - postgres_data:/var/lib/postgresql/data
    env_file:
      - ./habithub/.env

  habithub:
    image: habithub:latest
    container_name: web_django_habithub
    depends_on:
      - db
      - redis
      - celery
    volumes:
      - .:/app
      - static_volume:/app/staticfiles
    env_file:
      - ./habithub/.env
    command: >
      bash -c "python manage.py collectstatic --noinput && python manage.py migrate users && python manage.py migrate && gunicorn -b 0.0.0.0:8080 habithub.wsgi:application"
    ports:
      - "8080:8080"

  redis:
    image: "redis:alpine"
    container_name: redis_habits
    volumes:
      - redis_data:/data

  celery:
    build: .
    container_name: celery-worker
    command: celery -A habithub worker --loglevel=info
    depends_on:
      - redis
    env_file:
      - ./habithub/.env

  celery_beat:
    build: .
    container_name: celery-beat
    command: bash -c "python manage.py migrate django_celery_beat && celery -A habithub beat --loglevel=info"
    depends_on:
      - redis
    env_file:
      - ./habithub/.env
      
  nginx:
    build:
      dockerfile: ./Dockerfile
      context: ./docker/nginx
    container_name: habithub_nginx
    volumes:
      - static_volume:/app/staticfiles
    depends_on:
      - habithub
    ports:
      - "8081:80"

volumes:
  postgres_data:
  static_volume:
  redis_data:


