services:
  db:
    image: postgres:latest
    container_name: db_habits
    volumes:
      - postgres_data:/var/lib/postgresql/data
    env_file:
      - .env
  web:
    image: habits_docker:latest
    container_name: web_django
    depends_on:
      - db
    volumes:
      - .:/app
      - static_volume:/app/static
    env_file:
      - .env
    command: >
      bash -c "python manage.py collectstatic --noinput && gunicorn -b 0.0.0.0:8080 habithub.wsgi:application"
    ports:
      - "8080:8080"
  nginx:
    build:
      dockerfile: ./Dockerfile
      context: ./docker/nginx
    container_name: habithub_nginx
    volumes:
      - .:/app
      - static_volume:/app/static
    depends_on:
      - web
    ports:
      - "${NGINX_EXTERNAL_PORT}:80"

volumes:
  postgres_data:
  static_volume:


