# Generated by Django 5.1.2 on 2024-11-07 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Goal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('Активная', 'Active'), ('Достигнута', 'Completed'), ('В архиве', 'Archived')], default='Активная', max_length=20, verbose_name='Статус')),
                ('created_date', models.DateField(auto_now_add=True, verbose_name='Дата создания')),
                ('description', models.CharField(max_length=255, verbose_name='Описание цели')),
                ('target_date', models.DateTimeField(verbose_name='Дата достижения цели')),
            ],
            options={
                'verbose_name': 'Цели',
                'verbose_name_plural': 'Цели',
            },
        ),
        migrations.CreateModel(
            name='Habit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('Активная', 'Active'), ('Достигнута', 'Completed'), ('В архиве', 'Archived')], default='Активная', max_length=20, verbose_name='Статус')),
                ('created_date', models.DateField(auto_now_add=True, verbose_name='Дата создания')),
                ('name', models.CharField(max_length=100, verbose_name='Название привычки')),
                ('frequency', models.CharField(max_length=30, verbose_name='Частота выполнения')),
            ],
            options={
                'verbose_name': 'Привычки',
                'verbose_name_plural': 'Привычки',
            },
        ),
        migrations.CreateModel(
            name='HabitProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.BooleanField(choices=[(1, 'Выполнено'), (0, 'Не выполнено')], default=0, verbose_name='Статус выполнения')),
                ('date', models.DateField(verbose_name='Дата выполнения')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Заметки')),
            ],
        ),
        migrations.CreateModel(
            name='Remainders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reminder_time', models.TimeField(blank=True, verbose_name='Время напоминания')),
                ('reminder_frequency', models.CharField(blank=True, max_length=30, verbose_name='Частота напоминаний')),
                ('is_active', models.BooleanField(default=False, verbose_name='Активно')),
            ],
        ),
    ]
