# Generated by Django 5.1.2 on 2024-12-02 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habits', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goal',
            name='status',
            field=models.CharField(choices=[('Активная', 'Активная'), ('Достигнута', 'Достигнута'), ('В архиве', 'В архиве')], default='Активная', max_length=20, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='habit',
            name='status',
            field=models.CharField(choices=[('Активная', 'Активная'), ('Достигнута', 'Достигнута'), ('В архиве', 'В архиве')], default='Активная', max_length=20, verbose_name='Статус'),
        ),
    ]
