# Generated by Django 5.1.2 on 2024-12-24 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habits', '0004_alter_goal_target_date_delete_habitprogress'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='remainders',
            name='goal',
        ),
        migrations.AlterField(
            model_name='remainders',
            name='reminder_frequency',
            field=models.CharField(blank=True, choices=[('daily', 'Ежедневно'), ('weekly', 'Еженедельно'), ('monthly', 'Ежемесячно')], max_length=30, verbose_name='Частота напоминаний'),
        ),
    ]
