# Generated by Django 5.1.2 on 2025-03-13 15:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habits', '0005_remove_remainders_goal_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='remainders',
            name='habit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reminders', to='habits.habit', verbose_name='Привычка'),
        ),
    ]
